theme: jekyll-theme-hacker
title: That{Geeky}weeb 
    author :
      name : <Insert Legal Name Here>
      email : thatgeekyweeb@gmail.com
      github : ThatGeekyWeeb

kramdown:
  use_coderay: true

  coderay:
    coderay_line_numbers:
    coderay_tab_width: 2
    coderay_css: class
